# General Setting

[log]
level  = "INFO"  # from Ruby Logger::LEVEL
rotate = "daily" # from Ruby Logger shift_age
# file = /path/to/logfile

[api]
redis_url = 'redis://localhost:6379'

[worker]
redis_url = 'redis://localhost:6379'

[deliver]
min_interval = 60

[deliver.item]
merger = "Summary"

[database.connect]
url = 'sqlite://tmp/poloxy.sqlite.db'
