# General Setting

[log]
level  = "INFO"  # from Ruby Logger::LEVEL
rotate = "daily" # from Ruby Logger shift_age
# file = /path/to/logfile

[deliver]
min_interval = "1 min"

[deliver.item]
merger = "PerItem"

[smtp]
host = 'localhost'
port = 25

[database.connect]
url = 'sqlite://tmp/poloxy.sqlite.db'

[message]
default_expire = "2 hours"
default_snooze = "30 min"

[data]
default_keep_period = "2 days"
